### ISSUE TITLE
README documentation link error. 

### ISSUE THREAD

**Issue by Haris-AK** [vandyG/clickyaml#1]
* clickYaml version: 1.1.1
* Python version: 3.10.5
* Operating System: Windows 10

### Description

Error regarding the README. The documentation link (https://clickyaml.readthedocs.io/) does not return a valid documentation page:

![image](https://user-images.githubusercontent.com/81975456/217083445-71558f27-0f7d-439c-b368-2cf198364935.png)

**Comment by vandyG** [comment]
Hi, Thanks for submitting the issue. I am working on the documentations. Should be up soon.

**Comment by vandyG** [comment]
Hi, 
This has been fixed. The documentation is up and running.
